name: flutter_holo_date_picker
description: A Flutter package of Datepicker that looks like Holo Theme in Android.
version: 1.0.7
homepage: https://github.com/kfiross/flutter_holo_date_picker

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
